all: ;
	cd ARCS; $(MAKE) all
	cd BLT; $(MAKE) all
	cd CODES; $(MAKE) all
	cd COMBINATORICS; $(MAKE) all
	cd GRAPH; $(MAKE) all
	cd REGULAR_LS; $(MAKE) all
	cd TOOLS; $(MAKE) all
	cd TRANSLATION_PLANE; $(MAKE) all

clean: ;
	cd ARCS; $(MAKE) clean
	cd BLT; $(MAKE) clean
	cd CODES; $(MAKE) clean
	cd COMBINATORICS; $(MAKE) clean
	cd GRAPH; $(MAKE) clean
	cd REGULAR_LS; $(MAKE) clean
	cd TOOLS; $(MAKE) clean
	cd TRANSLATION_PLANE; $(MAKE) clean

